url: https://vinyltap.band

# Site settings
title: Vinyl Tap
email: philip.b.tyler@gmail.com
description: "LA's hottest cover band slinging 6 decades of rock, alternative, pop-punk, and new wave hits"


# Team names, titles and social links
people:
- name: Philip Tyler
  pic: 1
  position: Guitar & Vocals
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Arthur Siegel
  pic: 2
  position: Drums
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Peter Stewart
  pic: 3
  position: Guitar & Vocals
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Oren Ben-Joseph
  pic: 3
  position: Bass Guitar
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/this.is.vinyltap
  - title: instagram
    url: https://instram.com/this.is.vinyltap

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles, CA

# Build settings
markdown: kramdown
permalink: pretty