url: https://vinyltap.band/
image: img/card_image.jpg
thumbnail: img/thumbnail.jpg
site_title: "Vinyl Tap: LA's Hottest Cover Band"

# Site settings
title: Vinyl Tap
email: philip.b.tyler@gmail.com
description: "We are a professional cover band slinging 6 decades of rock, alternative, pop-punk, and new wave hits"

plugins:
  - jekyll-compress-images

# Team names, titles and social links
people:
- name: Philip Tyler
  pic: philip2019
  position: Guitar & Vocals
  social:
    - title: instagram
      url: https://instagram.com/thephiliptyler

- name: Arthur Siegel
  pic: arthur2019
  position: Drums
  social:
    - title: instagram
      url: https://instagram.com/gringo__starr

- name: Peter Stewart
  pic: peter2019
  position: Guitar & Vocals
  social:
    - title: instagram
      url: https://instagram.com/peter_m_stewart

- name: Oren Ben-Joseph
  pic: oren2019
  position: Bass & Vocals
  social:
    - title: instagram
      url: https://instagram.com/orenbj

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/this.is.vinyltap
  - title: instagram
    url: https://instram.com/this.is.vinyltap

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles, CA

# Build settings
markdown: kramdown
permalink: pretty